menu:
    Blog: /
    Archive: /archives/
    About: /about/
    # Weibo: http://weibo.com/sunchongsheng
    # Rss: /atom.xml

favicon: /favicon.jpg
logo: /favicon.jpg

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
